name: Continuous Delivery

on:
  push:
    branches:
      - master

jobs:
  cd:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    steps:
      - id: yarn-cache
        name: Get Yarn cache path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@722adc6
      - uses: actions/setup-node@1c5c137
        with:
          node-version: 12.x
      - uses: actions/cache@70655ec
        name: Load Yarn cache
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --ignore-scripts
        name: Install dependencies
      - run: yarn build
        name: Build bundle

      # Continuous Delivery Pipeline --

      - uses: codfish/semantic-release-action@a313b22
        name: Semantic Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn gen:version
        if: steps.semantic.outputs.new-release-published == 'true'
        name: Generate version file
      - run: yarn build
        if: steps.semantic.outputs.new-release-published == 'true'
        name: Re-build bundle with version info
      - run: yarn sign
        if: steps.semantic.outputs.new-release-published == 'true'
        name: Sign bundle
      - uses: dswistowski/surge-sh-action@341bcbd
        name: Deploy to Surge
        if: steps.semantic.outputs.new-release-published == 'true'
        with:
          domain: https://embed.chiffre.io
          project: ./dist
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
