name: Continuous Delivery

on:
  push:
    branches:
      - master

jobs:
  cd:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    steps:
      - id: yarn-cache
        name: Get Yarn cache path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - run: git fetch --prune --unshallow
      - uses: actions/setup-node@56899e050abffc08c2b3b61f3ec6a79a9dc3223d
        with:
          node-version: 14.x
      - uses: actions/cache@0781355a23dac32fd3bac414512f4b903437991a
        name: Load Yarn cache
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
        name: Install dependencies

      # Continuous Delivery Pipeline --

      # Build for NPM
      - run: yarn build:npm
        name: Build NPM package
      - run: yarn build:sha1
        name: Write Git SHA1 to file (for postinstall script)
      - uses: docker://ghcr.io/codfish/semantic-release-action@sha256:16ab6c16b1bff6bebdbcc6cfc07dfafff49d23c6818490500b8edb3babfff29e
        name: Semantic Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Build bundle to deploy
      - run: yarn build:bundle
        name: Build production bundle
        env:
          SIGNATURE_SECRET_KEY: ${{ secrets.SIGNATURE_SECRET_KEY }}
      - uses: dswistowski/surge-sh-action@341bcbd76a97da5e6b55ad92f53c0bf840e04c80
        name: Deploy to Surge
        with:
          domain: ${{ secrets.DEPLOYMENT_URL }}
          project: ./dist
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}

      - uses: 8398a7/action-slack@44a35a96508f31f916f99ad5b68f489ae45659a2
        name: Notify on Slack
        if: always() # Pick up events even if the job fails or is canceled.
        with:
          status: ${{ job.status }}
          author_name: Continuous Delivery
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
